components:
  schemas:
    V3_User:
      type: object
      properties:
        uuid:
          type: string
        is_admin:
          type: boolean
  responses:
    404NotFound:
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: string
              message:
                type: string
